# Listen on all container interfaces.
bind 0.0.0.0

# Redis default port.
port 6379

# Keep protected mode enabled.
protected-mode yes

# Disable persistence for the initial development stage.
# We can configure persistence when the production Redis architecture is finalized.
save ""

# Disable AOF for the initial development stage.
appendonly no

# Log level.
loglevel notice
